### ISSUE TITLE
Reduce size of notebooks

### ISSUE THREAD

**Issue by andreasnoack** [STOR-i/GaussianProcesses.jl#121]
We are working on reducing the size of a project which indirectly depends on this package and we noticed that 100MB are because of the notebooks checked into this package. Would it be possible to reduce that size? E.g. by checking in the notebooks without the output or by creating the notebooks as build artifacts from `jmd` files instead of checking them in. Thanks.

**Comment by chris-nemeth** [comment]
Hi @andreasnoack, thanks for raising this point. 

Are you using the newest version of the package? Previously, we did have some very large notebooks because of high-resolution figures. The new notebooks should have lower-resolution images and I think the total size of the /notebooks folder should now be about 2.5Mb.

**Comment by andreasnoack** [comment]
Ah, indeed I'm on 0.9. Great, then we just resolve this with an `] up`. Thanks.
