### ISSUE TITLE
Observation noise documentation error

### ISSUE THREAD

**Issue by dressel** [STOR-i/GaussianProcesses.jl#13]
In the 1-D regression example, `logObsNoise` is presented as "log standard deviation of noise", but in the code, this input is never multiplied by 2 when using `exp`. Also, the printout of a GP seems to indicate that logObsNoise should be a variance. I think it's inconsistent as is.

As a side note, should the fieldname be different? Like maybe `logNoiseVar`? It's longer and uglier, but explicit.

**Comment by fairbrot** [comment]
Thanks for pointing this out. We will be soon modifying the noise functionality so that a small amount of noise in the GP object is fixed for numerical stability, and allow additional noise to be optimized through (a more efficient) noise kernel.

I agree that the name logObsNoise is a bit misleading, so we will rename this appropriately.

**Comment by fairbrot** [comment]
Addressed in Issue #21
