### ISSUE TITLE
Bayesian parameter estimation

### ISSUE THREAD

**Issue by chris-nemeth** [STOR-i/GaussianProcesses.jl#18]
Create MCMC samplers to allow for Bayesian estimation of GP hyperparameters

**Comment by chris-nemeth** [comment]
Ongoing on the `nonGaussian` branch. Setting the priors is a little tricky at the moment and requires a better interface.

**Comment by chris-nemeth** [comment]
Currently using JuliaStats/Klara.jl for the MCMC. We could switch to brian-j-smith/Mamba.jl. Mamba has more functionality, but requires a GiovineItalia/Gadfly.jl dependency.

**Comment by chris-nemeth** [comment]
We now have our own MCMC implementation based on Hamiltonian Monte Carlo which samples from the posterior of the kernel/mean parameters in GPE and also the latent function in GPMC.

**Comment by Red-Portal** [comment]
@chris-nemeth  @thomaspinder 
Hi!
Some time has passed since HMC  was added to GaussianProcesses.jl,
what do you think about depending on more recent third-party HMC implementations?
The Turing.jl team has splitted their NUTS sampler into a separate repository [AdvancedHMC](https://github.com/TuringLang/AdvancedHMC.jl).
Depending on this could be an option?

**Comment by chris-nemeth** [comment]
Hi @Red-Portal, I spoke to one of the Turing.jl developers last week about this and I agree that it is something worth exploring. As mentioned above, we used to use Klara.jl, which is no longer supported, as this gave us a range of MCMC samplers to choose from. I think it should be quite easy to adapt our current MCMC scheme to depend on [AdvancedHMC](https://github.com/TuringLang/AdvancedHMC.jl). I won't have time to do this until next year, but I'm happy to support anyone else who would like to do this.

**Comment by Red-Portal** [comment]
Hi Chris, great!
I think I'll be able to do that once the semester is finished (about next week),
I plan on finishing the GP latent parameter sampler; then I could be able to look into AdvancedHMC.
How much control over the internals of AdvancedHMC do you think we need?
AdvancedHMC have much more knobs to turn.

**Comment by thomaspinder** [comment]
Hi @Red-Portal. I've set up an advancedHMC branch with dependencies added. I'm happy to work with you on this over the next few weeks to replace the current HMC with the AdvancedHMC functionalities. I think it would be useful to try and retain as much of the AdHMC functionalities as possilbe, otherwise the only benefit we'd be adding would be faster inference.

**Comment by Red-Portal** [comment]
Hi again @thomaspinder. Great! I'll start working right away.
BTW, seems like I mistakenly added a dependency on `ProgressMeter` in my last PR.
It doesn't seem to be used currently, but maybe adding a `ProgressMeter` visualization could be useful?
Otherwise the dependency should be removed.
