### ISSUE TITLE
Function for adding data to GP

### ISSUE THREAD

**Issue by bisraelsen** [STOR-i/GaussianProcesses.jl#27]
Is there a function for adding new observations to an existing GP?

**Comment by nemethis** [comment]
Not currently. At the moment you'd have to refit the GP with the new observations. One way forward here would be to modify the `GaussianProcesses.fit!(gp,x,y)` function. Currently this function will essentially refit the GP, but could be modified so that if the GP is non-empty it would instead update, rather than refit, the GP.

If you have a solution for this then we'd be interested to include it. I'll leave this issue open as a reminder to look at this again.

**Comment by bisraelsen** [comment]
See #31 

We may want to discuss further, because I feel like I may not be quite up to speed with the architecture of the code.
