### ISSUE TITLE
Time to draw samples grows quadratically with number of samples

### ISSUE THREAD

**Issue by mauro3** [STOR-i/GaussianProcesses.jl#40]
I would have thought that the time to draw samples grows linearly with the number of samples drawn (although I know next to nothing about GPs).  It seems to grow roughly quadratically (using setup from README "Sampling from the GP"):
```
julia> @time prior=rand(gp, linspace(-5,5,10), 10);
  0.000228 seconds (348 allocations: 10.891 KB)

julia> @time prior=rand(gp, linspace(-5,5,100), 10);
  0.002107 seconds (3.27 k allocations: 621.484 KB)

julia> @time prior=rand(gp, linspace(-5,5,1000), 10);
  0.112869 seconds (33.06 k allocations: 54.125 MB, 8.04% gc time)

julia> @time prior=rand(gp, linspace(-5,5,10000), 10);
 15.259130 seconds (339.22 k allocations: 5.223 GB, 2.18% gc time)
```
Is this correct?

**Comment by nemethis** [comment]
So there's a slight difference with the number of samples drawn (in this case 10) and the dimension of the covariance matrix. In the standard GP setting, fitting a GP is O(N^3) (due to matrix inversion). What you have here is sampling from a multivariate normal, say N(\mu,\Sigma), which is equivalent to \mu + \sqrt{\Sigma}*N(0,1). Now, in your example, you're increasing the dimension of \Sigma as 10, 10^2, 10^3, 10^4 and for each, you need to do a Cholesky decomposition (to get \sqrt{\Sigma}), which isn't linear in cost, and then multiply this by a matrix of random normals.

**Comment by mauro3** [comment]
Ok, my naive view was that it would sample gp to get one function and then evaluate that function at the points in linspace.  If I understand correctly, this is not fixable.
