### ISSUE TITLE
Reducing the size of epsilon

### ISSUE THREAD

**Issue by rcnlee** [STOR-i/GaussianProcesses.jl#86]
In GPE.jl lines 130 and 142, ``1e-5`` is used as an epsilon presumably to help numerical stability.  This might be large for certain applications though.  Should we change this to ``eps()``?

**Comment by maximerischard** [comment]
I agree 1e-5 is much too big and `eps()`, or a small multiple of `eps()`, might work quite well. There is actually a `tolerant_PDMat` utility function in GP.jl for this, but clearly I failed to replace every instance of this pattern in the package code. The heuristic in `tolerant_PDMat` is to add `ϵ = 1e-6*trace(Sigma_raw)/n` to the diagonal up to ten times, but I'm not sure where that idea has come from. `trace(Sigma_raw)/n` is the average eigenvalue, so I can see why that might be relevant, but 1e-6 seems arbitrary. Perhaps that should be `ϵ = eps()*trace(Sigma_raw)/n` but I'm not sufficiently well-versed in numerical methods to justify this choice.

@rcnlee, would you be able to put together a pull request together? This might include:
* moving `tolerant_PDMat` from GP.jl to utils.jl;
* using `tolerant_PDMat` in the lines of GPE.jl you found, and other relevant places;
* replacing the current heuristic with `ϵ = eps()` or `ϵ = eps()*trace(Sigma_raw)/n`, and experimenting with a few examples to see what works best.

@chris-nemeth, any thoughts on this?

**Comment by rcnlee** [comment]
@maximerischard For line 130 I see how I can replace with tolerant_PDMat.  But for line 142, I'm not sure what is going on there.  It eventually calls PDMat, but also providing chol.  Why not just let PDMats compute the cholesky factorization on construction?  Is it to save on allocations?

**Comment by chris-nemeth** [comment]
I agree that `eps()` seems sensible. When I first added the nugget term it was to improve the numerical stability of fitting the GP and this is quite a standard trick found in other packages. The value `1e-6` was arbitrary and not chosen for any specific reason. 

I suspect that `1e-5` could be removed from [line 142](https://github.com/STOR-i/GaussianProcesses.jl/blob/d8ca796954de06792e4010a1cdc991d6c83bd600/src/GPE.jl#L142) without causing a problem.

**Comment by devmotion** [comment]
Another definitely more expensive heuristic would be to (at least approximately) compute the nearest symmetric positive semidefinite matrix with respect to the Frobenius norm in case the Cholesky decomposition fails: https://www.sciencedirect.com/science/article/pii/0024379588902236 Sometimes when I had problems to figure out a good value for `ϵ` this heuristic worked quite reliably. In those cases numerical issues remained even after adding `1e-5` to the diagonal ten times, so it might be helpful if users could modify the value of `ϵ` and adapt it to their problems instead of hardcoding some (smaller or larger) fixed `ϵ`.
