### ISSUE TITLE
What's needed before tagging a version for julia v0.7?

### ISSUE THREAD

**Issue by maximerischard** [STOR-i/GaussianProcesses.jl#90]
I'm not up to speed on all the changes in julia v0.7. According to [the docs](https://docs.julialang.org/en/v0.7.0/stdlib/Pkg/), we should now have `Project.toml` and `Manifest.toml` files? Do they replace the `REQUIRE` file?

Is there anything else that needs to be done before we can tag a new version?

**Comment by fairbrot** [comment]
@devmotion please feel free to elaborate on the changes you have made to the package in the `NEWS.md` in the `v0.7` section which could be important for users to know about.

**Comment by fairbrot** [comment]
There's a slight compatibility issue with the  `Plots.jl` and `RecipesBase.jl` packages. The latest versions of both of these packages require `v0.1` whereas we only require `v0.7`. This means we would have to put an upper limit on the `RecipesBase.jl` package to be maintain compatibility with version julia `v0.7` which could cause compatibility issues (I believe the new virtual environments feature in Julia can help you get around dependency issues, but it could make the package more difficult to use).

As I see it there are two options we could take:

1. The simplest thing would be to just increase the requirement of Julia to `v1.0`. My worry here is that a lot of people may still be using `v0.7`.
2. We publish two versions of the package consecutively. A version `v0.7` which requires is compatible with Julia v0.7 (and has version limits for `RecipesBase.jl`), and then a `v0.8` which requires julia `v1.0`.

Does anyone have a view on this?

**Comment by chris-nemeth** [comment]
It looks like both options are pretty easy to do, but going with Option 2 is probably better as it covers Julia v0.7 and v1.0.

**Comment by chris-nemeth** [comment]
I've updated the notebooks and tested the package on Julia v0.7. Everything is working, so I suggest we go with @fairbrot second suggestion and publish this version for Julia v0.7 and I'll update the plots so we can publish a new version for Julia v1.0.

**Comment by devmotion** [comment]
Most of my changes were internal as far as I can see. Notable exceptions might be:
- adding dependency on `StatsFuns` and `SpecialFunctions`
- removing dependency on `Compat`
- renaming `FixedKern` to `FixedKernel`
- adding type parameters to `GPE`, `GPMC`, `ProdKernel`, and `SumKernel`, `ProdMean` and `SumMean`
- renaming fields of `GPE` and `GPE` (`x` instead of `X`, `mean` instead of `m`, `kernel` instead of `k`, and `nobs` instead of `nobsv`)
- renaming fields of `FixedKernel` and `Masked` (`kernel` instead of `kern`)
- renaming fields of `ProdKernel` and `SumKernel` (`kernels` instead of `kerns`)
- renaming keyword arguments of the `GPE` constructor to `kernel` and `mean`
- renaming `subkernels` and `submeans` to `components`

**Comment by devmotion** [comment]
I'm not completely sure anymore, I guess the main motivation was that with a lowercase `x` as fieldname uppercase `X` can be used as type parameter, similar to `y` and `Y`. By the way, I just noticed that lowercase `cK` denotes a matrix as well.

**Comment by fairbrot** [comment]
Versions v0.7 for Julia v0.7 and v0.8 for Julia v0.8 have now been released.

**Comment by maximerischard** [comment]
Superb. I assume you meant julia v1.0?

**Comment by fairbrot** [comment]
Yes! Corrected now.
