### ISSUE TITLE
Negative kernel lengths after optimize!

### ISSUE THREAD

**Issue by jbrea** [STOR-i/GaussianProcesses.jl#94]
For example
```julia
juila> using Random, GaussianProcesses
       Random.seed!(2)
       x = 5*randn(2, 10); y = 5*randn(10) .- 10                                              
       gp = GPE(x, y, MeanConst(-10.), SEArd([3., 3.], 5.))                                   
       GaussianProcesses.optimize!(gp, noise = false)                                         
       gp.kernel
Type: SEArd, Params: [-78.4947, -22.9623, 1.55072] 
```
Would it be better to use (box-)constrained optimization or optimize positive parameters in log-space?

**Comment by jbrea** [comment]
Sorry, I got confused. Looking at `set_params!` I see that this is in log-space.
But then, these are insane values for the length scale
```julia
julia> gp.kernel.iℓ2
2-element Array{Float64,1}:
 1.5121370244195386e68
 8.806154068359546e19
```
Wouldn't it make sense to restrict to some box nevertheless?
If for example the above gp is initialised with `MeanConst(0.)` and `SEArd([0., 0.], 2.)` the result of `optimize!` is more reasonable: `Type: SEArd, Params: [-0.465854, 1.82723, 1.62644]`.

**Comment by maximerischard** [comment]
Hmm, it's definitely true in my experience that the optimization is quite sensitive to initial parameters. I'm not an expert in optimization so there may well be things that can be done to improve the situation. Box constraints seem a little heavy-handed, and it's hard to think of good default values.

I'm going to close this issue because the title is confusing, but feel free to open a new issue if you want to discuss improvements to optimization more generally.
